"""add clinical history and shedding log

Revision ID: 314714c7d089
Revises: c107b3d3bd8d
Create Date: 2026-08-29 22:47:51.178543
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.base  # noqa: F401 - custom GUID/JSONType column types


revision: str = '314714c7d089'
down_revision: Union[str, None] = 'c107b3d3bd8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_histories',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('onset', sa.String(length=16), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('pattern', sa.String(length=16), nullable=True),
    sa.Column('family_history_hair_loss', sa.Boolean(), nullable=False),
    sa.Column('family_history_side', sa.String(length=16), nullable=True),
    sa.Column('thyroid_condition', sa.Boolean(), nullable=False),
    sa.Column('iron_deficiency', sa.Boolean(), nullable=False),
    sa.Column('autoimmune_condition', sa.Boolean(), nullable=False),
    sa.Column('pcos', sa.Boolean(), nullable=False),
    sa.Column('scalp_condition', sa.Boolean(), nullable=False),
    sa.Column('recent_illness', sa.Boolean(), nullable=False),
    sa.Column('recent_surgery', sa.Boolean(), nullable=False),
    sa.Column('major_stress', sa.Boolean(), nullable=False),
    sa.Column('rapid_weight_loss', sa.Boolean(), nullable=False),
    sa.Column('postpartum', sa.Boolean(), nullable=False),
    sa.Column('trigger_months_ago', sa.Integer(), nullable=True),
    sa.Column('medications', app.db.base.JSONType(), nullable=False),
    sa.Column('tight_hairstyles', sa.Boolean(), nullable=False),
    sa.Column('chemical_treatments', sa.Boolean(), nullable=False),
    sa.Column('heat_styling', sa.Boolean(), nullable=False),
    sa.Column('scalp_itch', sa.Boolean(), nullable=False),
    sa.Column('scalp_pain', sa.Boolean(), nullable=False),
    sa.Column('body_hair_change', sa.Boolean(), nullable=False),
    sa.Column('menstrual_irregularity', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clinical_histories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinical_histories_user_id'), ['user_id'], unique=True)

    op.create_table('shedding_logs',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('bucket', sa.String(length=16), nullable=True),
    sa.Column('context', sa.String(length=16), nullable=False),
    sa.Column('washed_hair', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shedding_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shedding_logs_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_shedding_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shedding_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shedding_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_shedding_logs_date'))

    op.drop_table('shedding_logs')
    with op.batch_alter_table('clinical_histories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinical_histories_user_id'))

    op.drop_table('clinical_histories')
    # ### end Alembic commands ###
