"""add validated flag to observations

Revision ID: 5153637a15a3
Revises: 314714c7d089
Create Date: 2026-08-29 23:04:12.556779
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.base  # noqa: F401 - custom GUID/JSONType column types


revision: str = '5153637a15a3'
down_revision: Union[str, None] = '314714c7d089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Existing rows were all produced by mock inference, so backfilling FALSE is
    # both correct and the safe default: a row can only become validated by
    # being re-analyzed with a model that passed the evaluation gate.
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('validated', sa.Boolean(), nullable=False, server_default=sa.false())
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_column('validated')

    # ### end Alembic commands ###
