"""add framing_match to image quality reports

Revision ID: c107b3d3bd8d
Revises: 0002_pgvector
Create Date: 2026-08-29 19:19:31.626981
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.base  # noqa: F401 - custom GUID/JSONType column types


revision: str = 'c107b3d3bd8d'
down_revision: Union[str, None] = '0002_pgvector'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_quality_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('framing_match', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_quality_reports', schema=None) as batch_op:
        batch_op.drop_column('framing_match')

    # ### end Alembic commands ###
