"""focused scans: optional subset of capture views

Revision ID: e994ab8f3960
Revises: d6bfebc41d0f
Create Date: 2026-09-29 15:44:13.331585
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.base  # noqa: F401 - custom GUID/JSONType column types


revision: str = 'e994ab8f3960'
down_revision: Union[str, None] = 'd6bfebc41d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('focus_views', app.db.base.JSONType(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_sessions', schema=None) as batch_op:
        batch_op.drop_column('focus_views')

    # ### end Alembic commands ###
