"""initial schema

Revision ID: fecd21625f17
Revises: 
Create Date: 2026-08-29 18:11:28.166480
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.base  # noqa: F401 - custom GUID/JSONType used in column defs


revision: str = 'fecd21625f17'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('actor_id', app.db.base.GUID(), nullable=True),
    sa.Column('user_id', app.db.base.GUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=48), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('meta', app.db.base.JSONType(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('evidence_documents',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('publisher', sa.String(length=160), nullable=False),
    sa.Column('pub_date', sa.Date(), nullable=True),
    sa.Column('evidence_grade', sa.String(length=32), nullable=False),
    sa.Column('domain', sa.String(length=8), nullable=False),
    sa.Column('deprecated', sa.Boolean(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('fitzpatrick_self', sa.Integer(), nullable=True),
    sa.Column('year_of_birth', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=16), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('consents',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consents_user_id'), ['user_id'], unique=False)

    op.create_table('evidence_chunks',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('document_id', app.db.base.GUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', app.db.base.JSONType(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['evidence_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_chunks_document_id'), ['document_id'], unique=False)

    op.create_table('products',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('manufacturer', sa.String(length=160), nullable=True),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('expiry', sa.String(length=32), nullable=True),
    sa.Column('batch', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('raw_ocr', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('jti')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('scan_sessions',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('domain', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('capture_protocol', sa.String(length=32), nullable=False),
    sa.Column('device_make', sa.String(length=64), nullable=True),
    sa.Column('lighting_label', sa.String(length=24), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('treatments',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('dose', sa.String(length=120), nullable=True),
    sa.Column('frequency', sa.String(length=120), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_prescribed_by_clinician', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('treatments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_treatments_user_id'), ['user_id'], unique=False)

    op.create_table('adherence_logs',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('treatment_id', app.db.base.GUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('taken', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('treatment_id', 'date', name='uq_adherence_per_day')
    )
    with op.batch_alter_table('adherence_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adherence_logs_treatment_id'), ['treatment_id'], unique=False)

    op.create_table('analyses',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('session_id', app.db.base.GUID(), nullable=False),
    sa.Column('skin_appearance_index', sa.Float(), nullable=True),
    sa.Column('hair_summary', app.db.base.JSONType(), nullable=True),
    sa.Column('overall_confidence', sa.Float(), nullable=False),
    sa.Column('llm_model', sa.String(length=48), nullable=False),
    sa.Column('explanation', app.db.base.JSONType(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['scan_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('comparisons',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('session_before', app.db.base.GUID(), nullable=False),
    sa.Column('session_after', app.db.base.GUID(), nullable=False),
    sa.Column('metrics', app.db.base.JSONType(), nullable=False),
    sa.Column('alignment_quality', sa.Float(), nullable=False),
    sa.Column('limitations', app.db.base.JSONType(), nullable=False),
    sa.Column('explanation', app.db.base.JSONType(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_after'], ['scan_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_before'], ['scan_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comparisons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comparisons_user_id'), ['user_id'], unique=False)

    op.create_table('product_ingredients',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('product_id', app.db.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('concentration', sa.String(length=48), nullable=True),
    sa.Column('is_potential_irritant', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of', sa.String(length=160), nullable=True),
    sa.Column('evidence_refs', app.db.base.JSONType(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_ingredients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_ingredients_product_id'), ['product_id'], unique=False)

    op.create_table('scan_images',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('session_id', app.db.base.GUID(), nullable=False),
    sa.Column('view', sa.String(length=24), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quality_passed', sa.Boolean(), nullable=True),
    sa.Column('alignment_json', app.db.base.JSONType(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['scan_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_images_session_id'), ['session_id'], unique=False)

    op.create_table('image_quality_reports',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('image_id', app.db.base.GUID(), nullable=False),
    sa.Column('blur_score', sa.Float(), nullable=False),
    sa.Column('exposure_score', sa.Float(), nullable=False),
    sa.Column('overexposed_frac', sa.Float(), nullable=False),
    sa.Column('distance_ok', sa.Boolean(), nullable=False),
    sa.Column('angle_ok', sa.Boolean(), nullable=False),
    sa.Column('scalp_visibility', sa.Float(), nullable=True),
    sa.Column('overall_pass', sa.Boolean(), nullable=False),
    sa.Column('reasons', app.db.base.JSONType(), nullable=False),
    sa.Column('retake_guidance', app.db.base.JSONType(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=48), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['scan_images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id')
    )
    op.create_table('observations',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('session_id', app.db.base.GUID(), nullable=False),
    sa.Column('image_id', app.db.base.GUID(), nullable=True),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('value_num', sa.Float(), nullable=True),
    sa.Column('value_label', sa.String(length=128), nullable=True),
    sa.Column('unit', sa.String(length=24), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_basis', sa.String(length=160), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=48), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('observation_type', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['scan_images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['scan_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observations_session_id'), ['session_id'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('analysis_id', app.db.base.GUID(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('evidence_refs', app.db.base.JSONType(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('requires_clinician', sa.Boolean(), nullable=False),
    sa.Column('is_prescription', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('is_prescription = 0', name='ck_no_autonomous_prescription'),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_analysis_id'), ['analysis_id'], unique=False)

    op.create_table('safety_verdicts',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('analysis_id', app.db.base.GUID(), nullable=False),
    sa.Column('verdict', sa.String(length=12), nullable=False),
    sa.Column('red_flags', app.db.base.JSONType(), nullable=False),
    sa.Column('triggered_rules', app.db.base.JSONType(), nullable=False),
    sa.Column('suppressed_cosmetic', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('safety_verdicts')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_analysis_id'))

    op.drop_table('recommendations')
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_session_id'))

    op.drop_table('observations')
    op.drop_table('image_quality_reports')
    with op.batch_alter_table('scan_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_images_session_id'))

    op.drop_table('scan_images')
    with op.batch_alter_table('product_ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_ingredients_product_id'))

    op.drop_table('product_ingredients')
    with op.batch_alter_table('comparisons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comparisons_user_id'))

    op.drop_table('comparisons')
    op.drop_table('analyses')
    with op.batch_alter_table('adherence_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adherence_logs_treatment_id'))

    op.drop_table('adherence_logs')
    with op.batch_alter_table('treatments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_treatments_user_id'))

    op.drop_table('treatments')
    with op.batch_alter_table('scan_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_scan_sessions_created_at'))

    op.drop_table('scan_sessions')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_user_id'))

    op.drop_table('products')
    with op.batch_alter_table('evidence_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_chunks_document_id'))

    op.drop_table('evidence_chunks')
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consents_user_id'))

    op.drop_table('consents')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('evidence_documents')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
